# ─────────────────────────────────────────────────────────────────────────────
#  core/plan_manager.py – Treatment plan drafting for Lana
#  Screens a dictated patient case against Alexandra's documented referral
#  criteria, drafts a phased plan grounded only in her documents, checks that
#  draft back against her contraindication rules, and renders a markdown file
#  for her review.
#
#  INVARIANT — THIS MODULE HAS NO DELIVERY PATH.
#  Its only side effect is writing a markdown file under data/treatment_plans/.
#  It imports no transport (smtplib, email_send, the Gmail API) and must never
#  gain one. Unlike the email send flow there is no irreversible act here, so
#  the catastrophic failures are content failures — a missed referral, an
#  unflagged contraindication, a silent guess where her documents are silent —
#  and that is where the engineering concentrates:
#
#    * No screening → no draft, ever (screen_case failing is fail-closed).
#    * Every drafted item cites a source; uncited items are flagged in Python,
#      not trusted.
#    * Every cited rule id is checked against the real rulebook, so a
#      hallucinated citation is caught deterministically.
#    * The DRAFT banner and her standing patient instructions are emitted by
#      the renderer, never generated by a model.
# ─────────────────────────────────────────────────────────────────────────────

from __future__ import annotations

import os
import re
import sys
from datetime import datetime

# Ensure the project root is on sys.path so `import config` works when this
# file is run directly (e.g. `python core/plan_manager.py`).
_PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _PROJECT_ROOT not in sys.path:
    sys.path.insert(0, _PROJECT_ROOT)

import anthropic
from loguru import logger

import config
from core.memory import EXTRACTION_MODEL_ID, extract_response_text, parse_json_object
from core.plan_knowledge import PlanKnowledge

# ── Storage ──────────────────────────────────────────────────────────────────
# data/ is git-ignored; drafts are patient-adjacent and never committed.
_DATA_DIR: str = os.path.join(_PROJECT_ROOT, "data")
_PLANS_DIR: str = os.path.join(_DATA_DIR, "treatment_plans")


def plans_dir() -> str:
    """
    Where saved drafts live. A function, not a re-exported constant, so the
    value is read at CALL time: scratchpad drive scripts repoint _PLANS_DIR at
    a temp dir before importing anything (see scratchpad/plan_drive.py), and a
    caller that bound the constant at import time would keep writing to — or
    serving from — the real data/ directory regardless.

    api/server.py's read-only plan endpoints go through here rather than
    reaching for the private name.
    """
    return _PLANS_DIR

# ── Models ───────────────────────────────────────────────────────────────────
# Realtime tier, same model core/llm.py and the email classifiers use. Defined
# locally rather than imported from email_manager: this module must not depend
# on the email module at all (scratchpad/plan_drive.py asserts that).
INTENT_MODEL_ID: str = "claude-haiku-4-5-20251001"
INTENT_MAX_TOKENS: int = 100
INTENT_TIMEOUT: float = 10.0
CONFIRM_MAX_TOKENS: int = 10

# Heavy tier for screening, drafting and checking — the house rule for any
# non-realtime reasoning task (see CLAUDE.md). max_retries=0 like the email
# reasoning client, because Alexandra is standing there waiting.
#
# THINKING IS DECLARED EXPLICITLY on every Sonnet call below, and these
# max_tokens values are sized for thinking + JSON together. Both matter:
#
#   * claude-sonnet-5 runs ADAPTIVE THINKING when `thinking` is omitted (Sonnet
#     4.6 ran thinking-off by omission). Relying on that default means a model
#     change silently alters safety-critical reasoning depth, so it is stated.
#   * max_tokens is a hard ceiling on TOTAL output — thinking tokens count
#     against it. Measured live: a screening call spent 1,360 output tokens to
#     emit 82 characters of JSON, i.e. ~1,335 went to thinking. An earlier
#     1500-token ceiling therefore truncated the JSON mid-object on most real
#     cases, and surfaced only as "unparseable output".
#
# Raising a ceiling costs nothing unless the tokens are used; truncating a
# safety screen costs a referral. Sized generously on purpose.
#
# The pinned anthropic==0.40.0 has no typed `thinking` parameter on
# messages.create(), so the declaration rides in extra_body — the SDK's
# escape hatch for body params it does not yet type. Adaptive is the server
# default for this model anyway; sending it explicitly is what keeps a future
# default change from silently altering how hard the safety screen thinks.
# When the SDK is bumped, move this to the typed parameter.
#
# ADAPTIVE IS 4.6-AND-LATER ONLY. Haiku 4.5 REJECTS {"type": "adaptive"} and
# errors on output_config.effort outright; it needs the older
# {"type": "enabled", "budget_tokens": N}, where N >= 1024 and N < that stage's
# max_tokens (the tightest is CHECK_MAX_TOKENS, so 4000 is the largest budget
# safe across all three stages). So retiering any stage to a pre-4.6 model is
# NEVER a model swap alone — this declaration has to change with it or the call
# 400s. That is what the constructor's `thinking=` override exists for.
_THINKING_BODY: dict = {"thinking": {"type": "adaptive"}}

# Per-stage heavy-tier models. All three default to the house background tier, so
# nothing changes unless a caller asks — but they are named separately for two
# reasons:
#
#   * EXTRACTION_MODEL_ID is SHARED with memory extraction (core/memory.py) and
#     email reasoning (core/email_manager.py). Retiering the plan pipeline by
#     editing that constant would silently retier those too.
#   * The stages do not carry equal risk. check_draft is the safety net behind
#     draft_plan, so downgrading the drafter is only defensible while the checker
#     stays heavy. One constant cannot express that; three can.
#
# Changing any of these invalidates the golden-suite evidence behind it until
# re-run — 0 referral misses (screening) and 0 contraindication escapes (check)
# are the bar, see scratchpad/PLAN_HANDOFF.md.
#
# BENCHMARKED 2026-07-28 — DO NOT RE-RUN "HAIKU FOR SPEED". Measured like-for-like
# on the golden suite with per-call instrumentation:
#
#     claude-sonnet-5      (adaptive)      26.8 s/call   $0.054/call   100% recall
#     claude-haiku-4-5-... (budget 4000)   26.1 s/call   $0.017/call   100% recall
#
# Haiku is NOT faster — 2.6% apart, inside noise. Thinking tokens dominate the
# wall clock and a cheaper model does not think less, so a tier downgrade does
# nothing for the ~2-minute revision silence; the levers for latency are thinking
# budget and corpus size, not the model. Haiku held 0 referral misses (29
# vignettes, 1 pass) and is ~3.2x cheaper, but raised two CONFIDENT false-positive
# referrals where Sonnet's recorded behaviour across 71 screenings was that every
# spurious flag self-identifies as "possible" — and "confident" is the signal the
# reviewing clinician triages on. No benefit, real regression: Sonnet stays.
# Haiku is only worth revisiting if COST, not speed, ever becomes the driver.
SCREEN_MODEL_ID: str = EXTRACTION_MODEL_ID
DRAFT_MODEL_ID: str = EXTRACTION_MODEL_ID
CHECK_MODEL_ID: str = EXTRACTION_MODEL_ID

SCREEN_MAX_TOKENS: int = 8000
SCREEN_TIMEOUT: float = 90.0
# 16000 was the non-streaming ceiling (above it, HTTP connections idle out). That
# constraint is gone now the call streams, and 16000 proved too low in practice:
# the warfarin case hit it and the draft was refused rather than truncated.
# Streaming supports far more; a ceiling costs nothing unless tokens are used.
DRAFT_MAX_TOKENS: int = 32000
DRAFT_TIMEOUT: float = 300.0
CHECK_MAX_TOKENS: int = 6000
CHECK_TIMEOUT: float = 90.0

# ── Intent + confirmation verdicts ───────────────────────────────────────────
INTENT_TREATMENT_PLAN: str = "treatment_plan"
INTENT_NOT_PLAN: str = "not_plan"

CONFIRM_YES: str = "yes"
CONFIRM_NO: str = "no"
CONFIRM_REVISE: str = "revise"
CONFIRM_UNCLEAR: str = "unclear"

# Verdicts for the referral gate's own question ("draft supportive care
# alongside the referral, or just save the note?"). A SEPARATE vocabulary from
# CONFIRM_* because it is a different question: the natural affirmative here is
# "draft the supportive care as well", which the save-this-draft classifier
# misreads as an edit ("revise") and so never drafts. Only REFERRAL_DRAFT draws
# a plan; everything else keeps the safe default (memo).
REFERRAL_DRAFT: str = "draft"
REFERRAL_NOTE: str = "note"
REFERRAL_UNCLEAR: str = "unclear"

# ── Draft plan-type verdicts ─────────────────────────────────────────────────
PLAN_TYPE_STANDARD: str = "standard"
PLAN_TYPE_UNIQUE: str = "unique"

# How squarely a referral flag matched. Presentational only — see the comment
# in _coerce_screening. Never used to decide whether a referral is raised.
CONFIDENCE_CONFIDENT: str = "confident"
CONFIDENCE_POSSIBLE: str = "possible"

# The seven timing columns of her supplement table, in her order. Keys are the
# draft-JSON field names; values are her exact column headers.
_TIMING_COLUMNS: tuple[tuple[str, str], ...] = (
    ("upon_waking", "Upon waking"),
    ("with_breakfast", "With breakfast"),
    ("mid_morning", "Mid Morning"),
    ("with_lunch", "With Lunch"),
    ("mid_afternoon", "Mid Afternoon"),
    ("with_dinner", "With Dinner"),
    ("before_bed", "Before Bed"),
)

_DRAFT_BANNER: str = (
    "> # ⚠ DRAFT — PENDING ALEXANDRA'S REVIEW\n"
    "> **This is a machine-generated draft. It has not been reviewed by a clinician "
    "and must not be given to a patient in this state.**"
)


class PlanManager:
    """
    Owns every LLM call and every file write for treatment-plan drafting.

    Construction is cheap; the caller must call load() (which loads the
    knowledge corpus) before anything else, and check `available`.
    """

    def __init__(
        self,
        knowledge: PlanKnowledge | None = None,
        *,
        screen_model: str | None = None,
        draft_model: str | None = None,
        check_model: str | None = None,
        thinking: dict | None = None,
    ) -> None:
        self._knowledge = knowledge or PlanKnowledge()

        # Two clients, mirroring EmailManager: a realtime one for the fast
        # classifiers and a reasoning one for screen/draft/check. Both
        # max_retries=0 — a silent SDK retry would double an already long wait.
        self._client = anthropic.Anthropic(api_key=config.ANTHROPIC_API_KEY, max_retries=0)
        self._reasoning_client = anthropic.Anthropic(
            api_key=config.ANTHROPIC_API_KEY, max_retries=0
        )

        # Keyword-only and defaulted, so production construction (PlanManager()
        # in assistant.py, and every drive script) is untouched. These exist so a
        # benchmark harness can retier ONE stage at a time without editing a
        # module constant that other subsystems share — see the SCREEN/DRAFT/
        # CHECK_MODEL_ID comment above. Overriding any of them means the safety
        # evidence for that stage no longer applies until the suite is re-run.
        self._screen_model = screen_model or SCREEN_MODEL_ID
        self._draft_model = draft_model or DRAFT_MODEL_ID
        self._check_model = check_model or CHECK_MODEL_ID
        # Thinking budget, same escape-hatch shape as _THINKING_BODY (adaptive by
        # default). A harness can pass {"thinking": {"type": "enabled",
        # "budget_tokens": N}} to trade reasoning depth for latency — the other
        # axis of the tier question, and equally evidence-invalidating.
        self._thinking = thinking or _THINKING_BODY

    # ── Lifecycle ─────────────────────────────────────────────────────────────

    def load(self) -> bool:
        """Load the knowledge corpus. Returns False if drafting is unavailable."""
        return self._knowledge.load()

    @property
    def available(self) -> bool:
        return self._knowledge.available

    @property
    def unavailable_reason(self) -> str:
        return self._knowledge.unavailable_reason

    @property
    def knowledge(self) -> PlanKnowledge:
        return self._knowledge

    # ── Prompt plumbing ───────────────────────────────────────────────────────

    def _cached_system(self, instructions: str) -> list[dict]:
        """
        Build the system prompt for a reasoning call: the full corpus as a
        cached prefix, then the per-call instructions.

        The corpus block is byte-identical across screen/draft/check, so one
        drafting session pays a single cache write and reads thereafter (~90%
        off the input cost of the later calls, and a faster first token).
        Correctness does not depend on the cache working — if the pinned SDK
        drops the cache_control key the calls still succeed at full price,
        which is what scratchpad/plan_cache_check.py exists to detect.
        """
        return [
            {
                "type": "text",
                "text": self._knowledge.corpus_block(),
                "cache_control": {"type": "ephemeral"},
            },
            {"type": "text", "text": instructions},
        ]

    # ── 1. Intent gate (Haiku) ────────────────────────────────────────────────

    def classify_plan_intent(self, text: str) -> dict:
        """
        Decide whether an utterance is asking for a treatment plan.

        Returns a fully-defaulted dict and never raises: any failure resolves
        to not_plan, so a classifier hiccup can never hijack a turn. Same
        contract as EmailManager.classify_intent.
        """
        fallback = {"intent": INTENT_NOT_PLAN, "patient_hint": None}
        if not text.strip():
            return fallback

        try:
            response = self._client.messages.create(
                model=INTENT_MODEL_ID,
                max_tokens=INTENT_MAX_TOKENS,
                timeout=INTENT_TIMEOUT,
                system=(
                    "You classify what a functional-medicine practitioner just said to her "
                    "voice assistant. Reply with ONLY a JSON object, no prose:\n"
                    '{"intent": "treatment_plan" | "not_plan", "patient_hint": string or null}\n\n'
                    "\"treatment_plan\" means she is describing a PATIENT CASE and wants a "
                    "treatment plan, protocol, or supplement plan drafted, or wants to know "
                    "whether a case should be referred out. Examples: \"draft a treatment plan "
                    "for a 34 year old with SIBO\", \"I've got a new patient, let me tell you "
                    "about her\", \"work up a protocol for this case\", \"should I refer this "
                    "one out?\".\n\n"
                    "\"not_plan\" means ANYTHING else. In particular:\n"
                    "- Anything about EMAIL is not_plan, even on a clinical subject "
                    "(\"draft an email to the lab about Sarah's results\", \"read me the "
                    "message about the treatment plan\", \"reply to the patient\"). Email is "
                    "handled elsewhere; misrouting it here breaks it.\n"
                    "- General chat, calendar, reminders, questions about her own schedule.\n"
                    "- Asking what a supplement does, with no patient case attached.\n\n"
                    "patient_hint: the patient's first name if she said one, else null. "
                    "Never invent a name.\n\n"
                    "If you are not confident it is a patient case needing a plan, answer "
                    "not_plan."
                ),
                messages=[{"role": "user", "content": text}],
            )
            parsed = parse_json_object(extract_response_text(response))
            if not parsed:
                return fallback

            intent = str(parsed.get("intent", "")).strip().lower()
            if intent != INTENT_TREATMENT_PLAN:
                return fallback

            hint = parsed.get("patient_hint")
            hint = hint.strip() if isinstance(hint, str) and hint.strip() else None
            return {"intent": INTENT_TREATMENT_PLAN, "patient_hint": hint}
        except Exception as exc:
            logger.warning(f"classify_plan_intent() failed ({exc}) - defaulting to not_plan.")
            return fallback

    # ── 2. Screening (Sonnet) ─────────────────────────────────────────────────

    def screen_case(self, case_text: str) -> dict | None:
        """
        Screen a case against her referral criteria and contraindication rules
        BEFORE any drafting happens.

        Returns None on failure — and None must be treated as fail-closed by
        the caller: no screening means no draft, ever. That is the difference
        between "I couldn't check this against your criteria" and quietly
        producing a wellness protocol for a case that needed a referral.
        """
        if not case_text.strip():
            return None

        instructions = (
            "You are screening a patient case for Alexandra, a functional medicine "
            "practitioner. You have her complete clinical documentation above. Screen the "
            "case she describes and reply with ONLY a JSON object:\n\n"
            "{\n"
            '  "patient_label": string,          // first name or short label, for the filename\n'
            '  "referral_flags": [               // EVERY referral rule this case triggers\n'
            '    {"rule_id": "REF-...", "matched_because": "what in the case triggers it",\n'
            '     "confidence": "confident" | "possible"}\n'
            "  ],\n"
            '  "plan_type": "standard" | "unique",\n'
            '  "standard_template_hint": string or null,  // e.g. "5R", "DUTCH high-androgen"\n'
            '  "applicable_rule_ids": ["CI-..."],// EVERY contraindication rule that applies\n'
            '  "missing_safety_fields": [string],// safety facts she did NOT state (see below)\n'
            '  "uncovered_topics": [string],     // aspects her documents do not cover\n'
            '  "reasoning": string               // 2-3 sentences, for her to read\n'
            "}\n\n"
            "RULES FOR EACH FIELD:\n\n"
            "referral_flags — check the case against EVERY REF-* rule. Flag a rule if the "
            "case plausibly meets it. MISSING a referral is the worst thing you can do here; "
            "flagging one she then dismisses costs her two seconds. When genuinely unsure, "
            "FLAG IT. Note that kind=test_first rules are not referrals of the whole case: "
            "they mean a specific intervention needs labs first. Flag them the same way.\n\n"
            "confidence — how squarely the case meets the rule. This changes only how the "
            "flag is PRESENTED to her; it never suppresses one, so it costs you nothing to "
            "flag something as \"possible\":\n"
            "  \"confident\" — the case states what the rule describes. For a rule naming "
            "several findings together (e.g. night sweats AND weight loss AND pain), all of "
            "them are present.\n"
            "  \"possible\"  — a partial or inferred match: only some findings of a cluster "
            "are present, the case hints at it without stating it, or the wording is "
            "ambiguous. Example: a rule about \"persistent fatigue despite mitochondrial and "
            "GI support\" is only \"confident\" if support was actually tried and failed — "
            "fatigue alone is \"possible\".\n"
            "Use \"possible\" freely. An over-flagged case where every flag claims certainty "
            "trains her to stop reading them, which is how a real referral gets missed.\n\n"
            "matched_because — quote or closely paraphrase the specific words in the case "
            "that triggered the rule. If you cannot point at anything concrete, the flag is "
            "\"possible\" at best.\n\n"
            "plan_type — apply her Standard vs Unique Plan Logic document.\n\n"
            "applicable_rule_ids — list every CI-* rule whose trigger the case matches "
            "(conditions, medications, or population). Include a rule even if the case does "
            "not currently mention the restricted substance; it constrains what may be drafted.\n\n"
            "missing_safety_fields — which of these she did NOT tell you, and that matter for "
            "THIS case: age, sex, weight, pregnancy status, kidney/liver/thyroid/autoimmune "
            "conditions, current medications, prior protocols tried. Only list what actually "
            "affects safe drafting here — do not demand a weight for a case where no dose "
            "depends on it.\n\n"
            "uncovered_topics — anything central to this case that her documentation does NOT "
            "cover. Her corpus has real gaps (functional blood-chemistry ranges; special "
            "populations such as cancer, MS and Crohn's; bowel resection; fibromyalgia; "
            "women's-health interventions beyond the DUTCH material). Naming a gap is CORRECT "
            "and expected — never paper over one with general medical knowledge.\n\n"
            "Cite only rule ids that appear in the rulebook above. Never invent an id."
        )

        try:
            response = self._reasoning_client.messages.create(
                model=self._screen_model,
                max_tokens=SCREEN_MAX_TOKENS,
                timeout=SCREEN_TIMEOUT,
                extra_body=self._thinking,
                system=self._cached_system(instructions),
                messages=[{"role": "user", "content": f"PATIENT CASE:\n{case_text}"}],
            )
            self._log_cache_usage(response, "screen_case")

            if getattr(response, "stop_reason", None) == "max_tokens":
                # Distinguished from a genuine parse failure because the fix is
                # completely different (raise the cap vs debug the prompt), and
                # a truncated screening is invisible otherwise — the JSON just
                # stops mid-object and looks like malformed output.
                logger.error(
                    f"screen_case() hit max_tokens ({SCREEN_MAX_TOKENS}) - the result was "
                    f"truncated. Failing closed."
                )
                return None

            parsed = parse_json_object(extract_response_text(response))
            if not parsed:
                logger.error("screen_case() returned unparseable output - failing closed.")
                return None
            return self._coerce_screening(parsed)
        except Exception as exc:
            logger.error(f"screen_case() failed ({exc}) - failing closed, no draft.")
            return None

    def _coerce_screening(self, parsed: dict) -> dict:
        """
        Normalize the screening result and drop hallucinated rule ids.

        A cited id that is not in the rulebook is discarded rather than
        trusted, and logged loudly — the model does not get to invent a rule
        and have it treated as one of hers.
        """
        known = self._knowledge.all_rule_ids()

        referral_ids = self._knowledge.referral_rule_ids()
        contra_ids = self._knowledge.contraindication_rule_ids()

        flags: list[dict] = []
        misfiled: list[str] = []
        for item in parsed.get("referral_flags") or []:
            if not isinstance(item, dict):
                continue
            rule_id = str(item.get("rule_id", "")).strip()
            if rule_id not in known:
                logger.warning(f"screen_case cited unknown referral rule {rule_id!r} - dropped.")
                continue
            if rule_id in contra_ids:
                # Observed live: the model puts CI-* rules in referral_flags.
                # A contraindication is not a referral — left uncorrected this
                # would tell Alexandra to refer a patient out because a
                # supplement needed a dose cap. Move it to where it belongs
                # rather than dropping it (the match itself is usually right).
                misfiled.append(rule_id)
                continue
            # Confidence is PRESENTATIONAL ONLY — it never gates whether the
            # referral branch fires. A "possible" flag still leads the
            # conversation and still lands above the plan in the document, so
            # recall is mathematically identical with or without this field.
            # It exists so 7-in-20 partial matches stop reading as certainties,
            # which is what trains someone to skim past the one that matters.
            # An absent or unrecognized value resolves to "confident": failing
            # toward prominence, never toward quiet.
            confidence = str(item.get("confidence", "")).strip().lower()
            if confidence not in (CONFIDENCE_CONFIDENT, CONFIDENCE_POSSIBLE):
                confidence = CONFIDENCE_CONFIDENT
            flags.append({
                "rule_id": rule_id,
                "matched_because": str(item.get("matched_because", "")).strip(),
                "confidence": confidence,
            })

        applicable: list[str] = []
        for rule_id in list(parsed.get("applicable_rule_ids") or []) + misfiled:
            rule_id = str(rule_id).strip()
            if rule_id not in known:
                logger.warning(f"screen_case cited unknown rule {rule_id!r} - dropped.")
                continue
            if rule_id in referral_ids:
                # The mirror-image error: a REF-* rule listed as a
                # contraindication. Promote it into referral_flags — dropping a
                # referral is the one failure this whole design exists to stop.
                if not any(f["rule_id"] == rule_id for f in flags):
                    flags.append({
                        "rule_id": rule_id,
                        "matched_because": "(listed under applicable rules by the screener)",
                        "confidence": CONFIDENCE_CONFIDENT,
                    })
                continue
            if rule_id not in applicable:
                applicable.append(rule_id)

        if misfiled:
            logger.info(f"screen_case misfiled {misfiled} as referrals - moved to applicable rules.")

        plan_type = str(parsed.get("plan_type", "")).strip().lower()
        if plan_type not in (PLAN_TYPE_STANDARD, PLAN_TYPE_UNIQUE):
            plan_type = PLAN_TYPE_UNIQUE  # unknown → the more cautious branch

        return {
            "patient_label": str(parsed.get("patient_label", "") or "patient").strip(),
            "referral_flags": flags,
            "plan_type": plan_type,
            "standard_template_hint": self._opt_str(parsed.get("standard_template_hint")),
            "applicable_rule_ids": applicable,
            "missing_safety_fields": self._str_list(parsed.get("missing_safety_fields")),
            "uncovered_topics": self._str_list(parsed.get("uncovered_topics")),
            "reasoning": str(parsed.get("reasoning", "")).strip(),
        }

    # ── 3. Drafting (Sonnet) ──────────────────────────────────────────────────

    def draft_plan(
        self,
        case_text: str,
        screening: dict,
        unresolved_fields: list[str] | None = None,
        prior_draft: dict | None = None,
        revision: str | None = None,
    ) -> dict | None:
        """
        Draft the plan itself. Returns structured JSON (never markdown) so the
        renderer, not the model, owns the document — the DRAFT banner, her
        table columns, and her standing patient instructions cannot be
        reworded or dropped by a drafting call.

        prior_draft + revision drive the revise loop: it EDITS the existing
        draft rather than starting over.
        """
        unresolved_fields = unresolved_fields or []

        rules_context = self._render_applicable_rules(screening.get("applicable_rule_ids", []))

        parts = [
            "You are drafting a treatment plan for Alexandra to review. Ground EVERY "
            "recommendation in her documentation above. Reply with ONLY a JSON object:\n\n"
            "{\n"
            '  "patient_label": string,\n'
            '  "summary_of_findings": string,        // findings + which test(s) they came from\n'
            '  "goals_timeline": {"total_months": string, "phase_count": number},\n'
            '  "phases": [{\n'
            '    "name": string,                     // e.g. "Phase 1 — Remove"\n'
            '    "duration_weeks": string,           // e.g. "4" or "2-4"\n'
            '    "supplements": [{\n'
            '      "product": string,                // prefer a product from her SEED formulary\n'
            '      "purpose": string,\n'
            '      "frequency": string,\n'
            '      "timing": {"upon_waking": "", "with_breakfast": "", "mid_morning": "",\n'
            '                 "with_lunch": "", "mid_afternoon": "", "with_dinner": "",\n'
            '                 "before_bed": ""},     // a count like "1", or "" if not then\n'
            '      "comments": string,\n'
            '      "source": string                  // e.g. "04_gut_repair_5r.md#phase-1-remove"\n'
            "    }],\n"
            '    "keep_supplements": [ ...same shape... ],  // things she should CONTINUE\n'
            '    "food_therapy": [{"food": ..., "purpose": ..., "frequency": ..., '
            '"comments": ..., "source": ...}],\n'
            '    "lifestyle_therapy": [{"lifestyle": ..., "purpose": ..., "frequency": ..., '
            '"comments": ..., "source": ...}]\n'
            "  }],\n"
            '  "testing_recommended": [string],\n'
            '  "next_appointment": string,\n'
            '  "not_covered_flags": [{"topic": string, "why": string}],\n'
            '  "safety_notes": [{"rule_id": "CI-...", "how_respected": string}]\n'
            "}\n\n"
            "NON-NEGOTIABLE RULES:\n\n"
            "1. GROUNDING. Every supplement, food and lifestyle item needs a \"source\" naming "
            "the document and section it comes from. If you cannot ground something in her "
            "documents, DO NOT include it as a recommendation — put it in not_covered_flags "
            "instead. Her documentation having a gap is a normal, expected outcome and she "
            "needs to know about it. Never fill a gap with general medical knowledge.\n\n"
            "2. CONTRAINDICATIONS. The rules listed below apply to this patient. Do not "
            "recommend anything they restrict. For each rule you had to work around, add a "
            "safety_notes entry saying how. Cite only real rule ids.\n\n"
            "3. PRODUCTS. Prefer products from her SEED formulary by their exact name. If a "
            "case needs something outside it, that is allowed — it will be flagged for her.\n\n"
            "4. PHASES. Follow the phase structure of whichever framework fits (5R, the DUTCH "
            "treatment phases, immune pre-protocol, gut-liver-skin), with her week ranges.\n\n"
            "5. TONE. Plans are addressed to the patient in second person, warm and plain.\n\n"
            "Do NOT write the document itself, any headers, any boilerplate, or any draft "
            "warning — only this JSON. The document is assembled separately."
        ]

        if rules_context:
            parts.append(f"\n\nCONTRAINDICATION RULES IN FORCE FOR THIS PATIENT:\n{rules_context}")

        if unresolved_fields:
            parts.append(
                "\n\nCAUTIOUS MODE — she did not confirm: "
                + ", ".join(unresolved_fields)
                + ".\nDo not assume a safe default for any of these (in particular, never "
                "assume a patient is not pregnant). Avoid anything whose safety depends on "
                "the unknown, and add a not_covered_flags entry for each one explaining what "
                "you avoided and why."
            )

        user_parts = [f"PATIENT CASE:\n{case_text}"]
        if screening.get("reasoning"):
            user_parts.append(f"\nSCREENING NOTES:\n{screening['reasoning']}")
        if screening.get("plan_type"):
            hint = screening.get("standard_template_hint") or "—"
            user_parts.append(
                f"\nPLAN TYPE: {screening['plan_type']} (framework hint: {hint})"
            )
        if screening.get("referral_flags"):
            flag_lines = "\n".join(
                f"- {f['rule_id']}: {f['matched_because']}"
                for f in screening["referral_flags"]
            )
            user_parts.append(
                "\nREFERRAL FLAGS ALREADY RAISED (the referral is handled separately and "
                "leads the document — draft supportive care that is appropriate ALONGSIDE "
                "it, and do not contradict or downplay it):\n" + flag_lines
            )
        if prior_draft and revision:
            user_parts.append(
                "\nYou previously produced the draft below. Alexandra asked for this change:\n"
                f"  \"{revision}\"\n"
                "EDIT that draft to satisfy her request. Keep everything she did not ask to "
                "change. Do not start over.\n\nPREVIOUS DRAFT:\n"
                + self._compact_draft_for_revision(prior_draft)
            )

        try:
            # STREAMED, unlike screen/check. Observed live: this call failed
            # with "Connection error." on every attempt while the smaller
            # screening call on the same connection succeeded. Drafting a full
            # plan means minutes of adaptive thinking before the first byte, and
            # a non-streaming HTTP connection idles out waiting for it. Streaming
            # keeps the connection active; get_final_message() still returns the
            # complete response, so nothing downstream changes.
            with self._reasoning_client.messages.stream(
                model=self._draft_model,
                max_tokens=DRAFT_MAX_TOKENS,
                timeout=DRAFT_TIMEOUT,
                extra_body=self._thinking,
                system=self._cached_system("".join(parts)),
                messages=[{"role": "user", "content": "\n".join(user_parts)}],
            ) as stream:
                response = stream.get_final_message()
            self._log_cache_usage(response, "draft_plan")

            if getattr(response, "stop_reason", None) == "max_tokens":
                # A truncated plan is worse than no plan: it looks complete and
                # silently drops whatever came last.
                logger.error("draft_plan() hit max_tokens - refusing to render a truncated plan.")
                return None

            parsed = parse_json_object(extract_response_text(response))
            if not parsed:
                logger.error("draft_plan() returned unparseable output.")
                return None
            return parsed
        except Exception as exc:
            logger.error(f"draft_plan() failed ({exc}).")
            return None

    # ── 4. Post-draft contraindication check (Sonnet) ─────────────────────────

    def check_draft(self, draft: dict, case_text: str, screening: dict) -> dict:
        """
        Re-check the finished draft against the contraindication rules that
        apply to this patient — a second pair of eyes on the drafter's work.

        Returns {"violations": [...], "checked": bool}. `checked` False means
        the check itself failed; the caller must surface that rather than
        treating an empty violation list as a clean bill of health.
        """
        empty = {"violations": [], "checked": False}

        items = self._extract_draft_items(draft)
        if not items:
            return {"violations": [], "checked": True}

        rules_context = self._render_applicable_rules(screening.get("applicable_rule_ids", []))
        if not rules_context:
            return {"violations": [], "checked": True}

        instructions = (
            "You are the safety check on a treatment plan that has already been drafted. "
            "Your ONLY job is to catch anything in the drafted item list that violates a "
            "contraindication rule in force for this patient. You are not reviewing quality, "
            "completeness, or clinical wisdom.\n\n"
            "Reply with ONLY a JSON object:\n"
            '{"violations": [{"rule_id": "CI-...", "item": "the drafted item", '
            '"phase": "which phase", "explanation": "one sentence"}]}\n\n'
            "An empty violations list is the correct answer when the draft is clean.\n\n"
            "Consider a violation to include: the restricted substance under a brand or "
            "product name; a dose above a rule's stated limit; a form the rule excludes "
            "(e.g. magnesium oxide where only bisglycinate or taurate is permitted); and a "
            "timing conflict where a rule requires separation. Cite only real rule ids."
        )

        try:
            response = self._reasoning_client.messages.create(
                model=self._check_model,
                max_tokens=CHECK_MAX_TOKENS,
                timeout=CHECK_TIMEOUT,
                extra_body=self._thinking,
                system=self._cached_system(instructions),
                messages=[{
                    "role": "user",
                    "content": (
                        f"PATIENT CASE:\n{case_text}\n\n"
                        f"CONTRAINDICATION RULES IN FORCE:\n{rules_context}\n\n"
                        f"DRAFTED ITEMS:\n{items}"
                    ),
                }],
            )
            self._log_cache_usage(response, "check_draft")
            parsed = parse_json_object(extract_response_text(response))
            if parsed is None:
                logger.error("check_draft() returned unparseable output.")
                return empty

            known = self._knowledge.all_rule_ids()
            violations = []
            for item in parsed.get("violations") or []:
                if not isinstance(item, dict):
                    continue
                rule_id = str(item.get("rule_id", "")).strip()
                if rule_id not in known:
                    logger.warning(f"check_draft cited unknown rule {rule_id!r} - dropped.")
                    continue
                violations.append({
                    "rule_id": rule_id,
                    "item": str(item.get("item", "")).strip(),
                    "phase": str(item.get("phase", "")).strip(),
                    "explanation": str(item.get("explanation", "")).strip(),
                })
            return {"violations": violations, "checked": True}
        except Exception as exc:
            logger.error(f"check_draft() failed ({exc}).")
            return empty

    # ── 5. Confirmation (Haiku) ───────────────────────────────────────────────

    def classify_plan_confirmation(self, answer_text: str) -> str:
        """
        Interpret her answer to "save this draft, or change something?".

        Same fail-closed shape as EmailManager.classify_confirmation, but note
        the safe direction differs: saving an inert, clearly-labelled draft
        file is not the risky outcome here — losing several minutes of dictated
        case to one garbled word is. So the CALLER treats exhausted-unclear as
        "save it and say so", while this classifier stays strict about what
        counts as an explicit yes/no/revise.
        """
        if not answer_text.strip():
            return CONFIRM_UNCLEAR  # no API call on silence

        try:
            response = self._client.messages.create(
                model=INTENT_MODEL_ID,
                max_tokens=CONFIRM_MAX_TOKENS,
                timeout=INTENT_TIMEOUT,
                system=(
                    "A voice assistant just summarised a drafted treatment plan and asked the "
                    "practitioner whether to save it as a draft for her review, or change "
                    "something first. Reply with ONLY one lowercase word:\n"
                    "- \"yes\" if she clearly wants it saved as-is (\"yes\", \"save it\", "
                    "\"that's good\", \"perfect\", \"go ahead\").\n"
                    "- \"no\" if she clearly does not want it kept (\"no\", \"scrap it\", "
                    "\"bin it\", \"start over\", \"forget it\").\n"
                    "- \"revise\" if she wants the PLAN CHANGED — any edit to a supplement, "
                    "dose, phase, food, timing or wording (\"drop the magnesium\", \"make it "
                    "three phases\", \"add zinc\", \"yes but shorten phase two\").\n"
                    "- \"unclear\" for anything else: hesitation, a question back, an "
                    "unrelated remark, or anything you are not confident about.\n\n"
                    "Output only that one word."
                ),
                messages=[{"role": "user", "content": answer_text}],
            )
            verdict = extract_response_text(response).strip().lower()
            for candidate in (CONFIRM_REVISE, CONFIRM_YES, CONFIRM_NO):
                if verdict.startswith(candidate):
                    return candidate
            return CONFIRM_UNCLEAR
        except Exception as exc:
            logger.warning(f"classify_plan_confirmation() failed ({exc}) - 'unclear'.")
            return CONFIRM_UNCLEAR

    def classify_referral_followup(self, answer_text: str) -> str:
        """
        Interpret her answer to the REFERRAL-GATE question: "draft supportive
        care alongside the referral, or just save the referral note?"

        This is a different question from classify_plan_confirmation's, and
        needs its own classifier. The natural affirmative here — "draft the
        supportive care as well" — contains the word "draft"/"add", which the
        save-this-draft classifier reads as an EDIT ("revise") and therefore
        never treats as a yes, so a practitioner asking for a plan silently got
        a memo instead (a real bug found on camera).

        Fail-closed the safe way for a FLAGGED case: only a clear REFERRAL_DRAFT
        draws a plan. Silence (no API call), an ambiguous answer, or an
        exception all return a non-draft verdict, so the caller keeps the
        memo-only default. Mirrors classify_plan_confirmation's shape.
        """
        if not answer_text.strip():
            return REFERRAL_UNCLEAR  # no API call on silence

        try:
            response = self._client.messages.create(
                model=INTENT_MODEL_ID,
                max_tokens=CONFIRM_MAX_TOKENS,
                timeout=INTENT_TIMEOUT,
                system=(
                    "A voice assistant screened a patient case, found referral flags, and "
                    "asked the practitioner: \"Do you want me to draft supportive care "
                    "alongside the referral, or just save the referral note?\" Reply with "
                    "ONLY one lowercase word:\n"
                    "- \"draft\" if she wants a supportive-care treatment plan drafted in "
                    "addition to the referral (\"draft the supportive care as well\", \"yes, "
                    "draft it too\", \"go ahead and draft a plan\", \"draft supportive care\", "
                    "\"both\", \"draft it\", \"yes\").\n"
                    "- \"note\" if she wants ONLY the referral note and no plan (\"just the "
                    "note\", \"just save the referral\", \"only the referral note\", \"no "
                    "plan\", \"no\").\n"
                    "- \"unclear\" for anything else: hesitation, a question back, an "
                    "unrelated remark, or anything you are not confident about.\n\n"
                    "Output only that one word."
                ),
                messages=[{"role": "user", "content": answer_text}],
            )
            verdict = extract_response_text(response).strip().lower()
            for candidate in (REFERRAL_DRAFT, REFERRAL_NOTE, REFERRAL_UNCLEAR):
                if verdict.startswith(candidate):
                    return candidate
            return REFERRAL_UNCLEAR
        except Exception as exc:
            logger.warning(f"classify_referral_followup() failed ({exc}) - 'unclear'.")
            return REFERRAL_UNCLEAR

    # ── Draft integrity (Python, not the model) ───────────────────────────────

    def validate_draft(self, draft: dict) -> list[str]:
        """
        Deterministic integrity pass over a draft. Returns human-readable
        warnings that the renderer surfaces in the flags section.

        This is where a hallucinated source or rule id gets caught: the model
        is asked to cite, and Python checks the citations against the real
        corpus rather than trusting them.
        """
        warnings: list[str] = []
        known_sources = set(self._knowledge._sources)  # filenames
        known_rules = self._knowledge.all_rule_ids()

        for phase in draft.get("phases") or []:
            phase_name = str(phase.get("name", "?"))
            for bucket, label_key in (
                ("supplements", "product"),
                ("keep_supplements", "product"),
                ("food_therapy", "food"),
                ("lifestyle_therapy", "lifestyle"),
            ):
                for item in phase.get(bucket) or []:
                    if not isinstance(item, dict):
                        continue
                    label = str(item.get(label_key, "") or "?").strip()

                    source = str(item.get("source", "") or "").strip()
                    fname = source.split("#", 1)[0]
                    if not source:
                        warnings.append(f"{phase_name} · {label}: no source cited — VERIFY")
                    elif fname not in known_sources:
                        warnings.append(
                            f"{phase_name} · {label}: cites \"{source}\", which is not one of "
                            f"your documents — VERIFY"
                        )

                    if bucket in ("supplements", "keep_supplements"):
                        if not self._knowledge.formulary_match(label):
                            warnings.append(
                                f"{phase_name} · {label}: not matched in your SEED formulary "
                                f"(may be intentional, or may be an unclear product name)"
                            )

        for note in draft.get("safety_notes") or []:
            if not isinstance(note, dict):
                continue
            rule_id = str(note.get("rule_id", "")).strip()
            if rule_id and rule_id not in known_rules:
                warnings.append(f"safety note cites unknown rule {rule_id} — VERIFY")

        if not draft.get("phases"):
            warnings.append("draft contains no phases")

        return warnings

    # ── Rendering ─────────────────────────────────────────────────────────────

    def render_markdown(
        self,
        draft: dict,
        screening: dict,
        violations: list[dict],
        integrity_warnings: list[str],
        case_text: str,
        check_ran: bool = True,
    ) -> str:
        """
        Assemble the draft document.

        The banner, provenance, referral section, warnings and her verbatim
        boilerplate are all emitted here in Python. No model output can omit
        them or reword them.
        """
        out: list[str] = []
        w = out.append
        boiler = self._knowledge.template_boilerplate()

        w(_DRAFT_BANNER)
        w("")

        # ── Provenance ────────────────────────────────────────────────────────
        now = datetime.now(config.TIMEZONE)
        w("| | |")
        w("| --- | --- |")
        w(f"| Generated | {now.strftime('%d %b %Y, %H:%M')} |")
        w(f"| Corpus | `{self._knowledge.corpus_hash()}` |")
        w(f"| Rules | v{self._knowledge.rules_version} |")
        # The DRAFT model specifically — this table says how this document was
        # produced, and the drafter is what wrote it. Identical to the old
        # EXTRACTION_MODEL_ID output unless a caller retiered the draft stage.
        w(f"| Model | `{self._draft_model}` |")
        w(f"| Plan type | {screening.get('plan_type', '?')} |")
        w("")
        if not self._knowledge.rules_reviewed:
            w("> **The safety rules behind this draft have not been clinically reviewed yet.** "
              "The quoted criteria are verified against the source documents; the scoping "
              "around them has not been confirmed.")
            w("")

        # ── Referral — always above the plan ──────────────────────────────────
        flags = screening.get("referral_flags") or []
        if flags:
            confident, possible = self.split_flags_by_confidence(flags)

            w("## 🚩 REFERRAL INDICATED")
            w("")
            if confident:
                w("This case matches referral criteria in your own documentation:")
                w("")
                self._render_flags(w, confident)
            if possible:
                w("### Also worth checking")
                w("")
                w("Partial or inferred matches — not squarely met, but close enough to "
                  "surface rather than drop:")
                w("")
                self._render_flags(w, possible)
            w("---")
            w("")

        # ── Contraindication warnings ─────────────────────────────────────────
        if violations:
            w("## ⛔ CONTRAINDICATION WARNINGS — UNRESOLVED")
            w("")
            w("The post-draft check flagged these and a revision did not clear them. "
              "**Review before using anything below.**")
            w("")
            for v in violations:
                rule = self._knowledge.rule(v["rule_id"])
                w(f"- **{v.get('item', '?')}** ({v.get('phase', '?')}) — "
                  f"`{v['rule_id']}`: {v.get('explanation', '')}")
                if rule:
                    w(f"  > {rule['verbatim']}")
            w("")
            w("---")
            w("")
        elif not check_ran:
            w("## ⚠ CONTRAINDICATION CHECK DID NOT RUN")
            w("")
            w("The automated post-draft safety check failed to complete, so this draft has "
              "**not** been machine-checked against your contraindication rules. Treat it as "
              "unchecked.")
            w("")
            w("---")
            w("")

        # ── The plan itself ───────────────────────────────────────────────────
        w(f"**Patient:** {draft.get('patient_label', screening.get('patient_label', ''))}")
        w("")
        w(f"**Evaluation Date:** {now.strftime('%d.%m.%Y')}")
        w("")
        w("**Practitioner:** Alexa")
        w("")

        goals = draft.get("goals_timeline") or {}
        if goals:
            w("## Goals & Timeline")
            w("")
            w(f"Approximately {goals.get('total_months', 'X')} months in total, "
              f"divided into {goals.get('phase_count', 'X')} phases.")
            w("")

        for phase in draft.get("phases") or []:
            w(f"## {phase.get('name', 'Phase')}")
            w("")
            duration = phase.get("duration_weeks", "")
            if duration:
                w(f"*Duration: {duration} weeks*")
                w("")

            self._render_supplement_table(
                w, phase.get("supplements"), f"Supplement Recommendations ({duration} WEEKS)"
            )
            self._render_supplement_table(w, phase.get("keep_supplements"), "KEEP")

            self._render_simple_table(
                w, phase.get("food_therapy"), f"Food Therapy ({duration} WEEKS)",
                "Food", "food",
            )
            self._render_simple_table(
                w, phase.get("lifestyle_therapy"), f"Lifestyle Therapy ({duration} WEEKS)",
                "Lifestyle", "lifestyle",
            )

        if draft.get("summary_of_findings"):
            w("## Summary of Findings & Treatment")
            w("")
            w(str(draft["summary_of_findings"]))
            w("")

        if draft.get("testing_recommended"):
            w("## TESTING")
            w("")
            for test in draft["testing_recommended"]:
                w(f"- {test}")
            w("")

        # ── Her verbatim boilerplate — emitted here, never generated ──────────
        w("---")
        w("")
        w(boiler["general_recommendations"])
        w("")
        if draft.get("next_appointment"):
            w(f"**Next Appointment:** {draft['next_appointment']}")
            w("")
        w(boiler["the_process"])
        w("")

        # ── Gaps and integrity ────────────────────────────────────────────────
        gaps = draft.get("not_covered_flags") or []
        missing = screening.get("missing_safety_fields") or []
        uncovered = screening.get("uncovered_topics") or []

        if gaps or missing or uncovered or integrity_warnings:
            w("---")
            w("")
            w("## ⚑ NOT COVERED BY YOUR DOCUMENTS")
            w("")
            w("Everything below is flagged rather than guessed at.")
            w("")
            if uncovered:
                w("**Your documentation does not cover:**")
                w("")
                for topic in uncovered:
                    w(f"- {topic}")
                w("")
            if gaps:
                w("**Left out of the plan for that reason:**")
                w("")
                for gap in gaps:
                    if isinstance(gap, dict):
                        w(f"- **{gap.get('topic', '?')}** — {gap.get('why', '')}")
                w("")
            if missing:
                w("**Not confirmed during dictation (drafted cautiously around these):**")
                w("")
                for field in missing:
                    w(f"- {field}")
                w("")
            if integrity_warnings:
                w("**Automated integrity checks:**")
                w("")
                for warning in integrity_warnings:
                    w(f"- {warning}")
                w("")

        # ── Grounding appendix ────────────────────────────────────────────────
        w("---")
        w("")
        w("## Grounding")
        w("")
        w("Where each recommendation came from in your documentation.")
        w("")
        sources_seen: list[tuple[str, str]] = []
        for phase in draft.get("phases") or []:
            for bucket, key in (("supplements", "product"), ("keep_supplements", "product"),
                                ("food_therapy", "food"), ("lifestyle_therapy", "lifestyle")):
                for item in phase.get(bucket) or []:
                    if isinstance(item, dict) and item.get("source"):
                        sources_seen.append((str(item.get(key, "?")), str(item["source"])))
        if sources_seen:
            w("| Item | Source |")
            w("| --- | --- |")
            for label, source in sources_seen:
                w(f"| {self._cell(label)} | `{self._cell(source)}` |")
            w("")

        notes = draft.get("safety_notes") or []
        if notes:
            w("### Contraindication rules applied")
            w("")
            for note in notes:
                if not isinstance(note, dict):
                    continue
                rule = self._knowledge.rule(str(note.get("rule_id", "")))
                w(f"- **`{note.get('rule_id', '?')}`** — {note.get('how_respected', '')}")
                if rule:
                    w(f"  > {rule['verbatim']}")
            w("")

        w("---")
        w("")
        w(_DRAFT_BANNER)
        w("")

        return "\n".join(out)

    @staticmethod
    def split_flags_by_confidence(flags: list[dict]) -> tuple[list[dict], list[dict]]:
        """
        Partition referral flags into (confident, possible).

        Both halves are always shown — this splits presentation, not substance.
        Callers must never treat an empty `confident` list as "no referral".
        """
        confident = [f for f in flags
                     if f.get("confidence", CONFIDENCE_CONFIDENT) != CONFIDENCE_POSSIBLE]
        possible = [f for f in flags if f.get("confidence") == CONFIDENCE_POSSIBLE]
        return confident, possible

    def _render_flags(self, w, flags: list[dict]) -> None:
        for flag in flags:
            rule = self._knowledge.rule(flag["rule_id"])
            if not rule:
                continue
            kind = rule.get("kind", "refer_out")
            label = "REFER OUT" if kind == "refer_out" else "TEST FIRST"
            w(f"#### `{flag['rule_id']}` · {label} → {rule.get('refer_to', '')}")
            w("")
            w(f"> {rule['verbatim']}")
            w("")
            w(f"**In this case:** {flag.get('matched_because', '')}")
            w("")

    def render_referral_memo(self, screening: dict, case_text: str) -> str:
        """
        The document produced when a referral-flagged case does NOT get a plan.

        This is the default outcome for a flagged case: a plan only follows an
        explicit yes from Alexandra.
        """
        out: list[str] = []
        w = out.append
        now = datetime.now(config.TIMEZONE)

        w("> # ⚠ REFERRAL NOTE — DRAFT, PENDING ALEXANDRA'S REVIEW")
        w("> **Machine-generated. No treatment plan was drafted for this case.**")
        w("")
        w(f"**Patient:** {screening.get('patient_label', '')}")
        w("")
        w(f"**Date:** {now.strftime('%d %b %Y, %H:%M')}")
        w("")
        confident, possible = self.split_flags_by_confidence(
            screening.get("referral_flags") or []
        )
        if confident:
            w("## Referral criteria matched")
            w("")
            self._render_flags(w, confident)
        if possible:
            w("## Also worth checking")
            w("")
            w("Partial or inferred matches:")
            w("")
            self._render_flags(w, possible)

        if screening.get("reasoning"):
            w("## Screening notes")
            w("")
            w(screening["reasoning"])
            w("")

        w("## Case as dictated")
        w("")
        w("```")
        w(case_text.strip())
        w("```")
        w("")
        w("---")
        w("")
        w("*No treatment plan was drafted. Ask Lana to draft supportive care alongside the "
          "referral if that's appropriate for this patient.*")
        w("")

        return "\n".join(out)

    # ── Persistence ───────────────────────────────────────────────────────────

    def save_draft(self, markdown: str, patient_label: str) -> str | None:
        return self._save(markdown, patient_label, "DRAFT_plan")

    def save_referral_memo(self, markdown: str, patient_label: str) -> str | None:
        return self._save(markdown, patient_label, "DRAFT_referral_memo")

    def _save(self, markdown: str, patient_label: str, prefix: str) -> str | None:
        """
        Atomic write, same idiom as memory.py's _write_locked (tmp + os.replace).
        No lock is needed: conversations are strictly serial by construction, so
        there is only ever one writer.
        """
        try:
            os.makedirs(_PLANS_DIR, exist_ok=True)
            timestamp = datetime.now(config.TIMEZONE).strftime("%Y%m%d-%H%M%S")
            filename = f"{prefix}_{self._slugify(patient_label)}_{timestamp}.md"
            path = os.path.join(_PLANS_DIR, filename)
            tmp_path = path + ".tmp"
            with open(tmp_path, "w", encoding="utf-8", newline="\n") as f:
                f.write(markdown)
            os.replace(tmp_path, path)
            logger.success(f"Treatment plan draft saved: {path}")
            return path
        except OSError as exc:
            logger.error(f"Failed to save treatment plan draft: {exc}")
            return None

    # ── Helpers ───────────────────────────────────────────────────────────────

    def _render_supplement_table(self, w, items, title: str) -> None:
        if not items:
            return
        w(f"### {title}")
        w("")
        headers = ["Supplement", "Purpose", "Frequency"] + [c for _, c in _TIMING_COLUMNS] + ["Comments"]
        w("| " + " | ".join(headers) + " |")
        w("| " + " | ".join(["---"] * len(headers)) + " |")
        for item in items:
            if not isinstance(item, dict):
                continue
            timing = item.get("timing") or {}
            row = [
                self._cell(item.get("product", "")),
                self._cell(item.get("purpose", "")),
                self._cell(item.get("frequency", "")),
            ]
            row += [self._cell(timing.get(key, "")) for key, _ in _TIMING_COLUMNS]
            row.append(self._cell(item.get("comments", "")))
            w("| " + " | ".join(row) + " |")
        w("")

    def _render_simple_table(self, w, items, title: str, header: str, key: str) -> None:
        if not items:
            return
        w(f"### {title}")
        w("")
        w(f"| {header} | Purpose | Frequency | Comments |")
        w("| --- | --- | --- | --- |")
        for item in items:
            if not isinstance(item, dict):
                continue
            w("| " + " | ".join([
                self._cell(item.get(key, "")),
                self._cell(item.get("purpose", "")),
                self._cell(item.get("frequency", "")),
                self._cell(item.get("comments", "")),
            ]) + " |")
        w("")

    @staticmethod
    def _cell(value) -> str:
        """Make a value safe inside a markdown table cell."""
        text = str(value if value is not None else "").strip()
        return text.replace("|", "\\|").replace("\n", " ")

    @staticmethod
    def _slugify(text: str) -> str:
        """
        Filename-safe patient label. Deliberately short — data/ syncs to
        OneDrive, so a first name or initials is all that should be in a
        filename.
        """
        slug = re.sub(r"[^a-zA-Z0-9]+", "-", str(text or "patient")).strip("-").lower()
        return (slug or "patient")[:24]

    @staticmethod
    def _opt_str(value) -> str | None:
        return value.strip() if isinstance(value, str) and value.strip() else None

    @staticmethod
    def _str_list(value) -> list[str]:
        if not isinstance(value, list):
            return []
        return [str(v).strip() for v in value if str(v).strip()]

    def _render_applicable_rules(self, rule_ids: list[str]) -> str:
        """Render the subset of rules in force for this patient, for a prompt."""
        lines = []
        for rule_id in rule_ids:
            rule = self._knowledge.rule(rule_id)
            if not rule:
                continue
            restricted = "; ".join(
                f"{item.get('item', '')} → {item.get('action', '')}"
                + (f" (limit {item['limit']})" if item.get("limit") else "")
                + (f" [{item['note']}]" if item.get("note") else "")
                for item in rule.get("restricted", [])
            )
            lines.append(
                f"[{rule_id}] {restricted}\n"
                f"    her words: \"{rule['verbatim']}\""
            )
        return "\n".join(lines)

    @staticmethod
    def _extract_draft_items(draft: dict) -> str:
        """Flatten the drafted items into the list the checker reasons over."""
        lines = []
        for phase in draft.get("phases") or []:
            phase_name = str(phase.get("name", "Phase"))
            for bucket, key in (("supplements", "product"), ("keep_supplements", "product"),
                                ("food_therapy", "food"), ("lifestyle_therapy", "lifestyle")):
                for item in phase.get(bucket) or []:
                    if not isinstance(item, dict):
                        continue
                    timing = item.get("timing") or {}
                    when = ", ".join(
                        f"{label} {timing[key_]}" for key_, label in _TIMING_COLUMNS
                        if str(timing.get(key_, "")).strip()
                    )
                    lines.append(
                        f"- [{phase_name}] {item.get(key, '?')} — "
                        f"{item.get('frequency', '')} {when} — {item.get('comments', '')}"
                    )
        return "\n".join(lines)

    @staticmethod
    def _compact_draft_for_revision(draft: dict) -> str:
        """A compact view of a prior draft, so the revise call edits rather than restarts."""
        lines = []
        for phase in draft.get("phases") or []:
            lines.append(f"{phase.get('name', 'Phase')} ({phase.get('duration_weeks', '?')} weeks)")
            for bucket, key in (("supplements", "product"), ("keep_supplements", "product"),
                                ("food_therapy", "food"), ("lifestyle_therapy", "lifestyle")):
                for item in phase.get(bucket) or []:
                    if isinstance(item, dict):
                        lines.append(
                            f"  - [{bucket}] {item.get(key, '?')}: "
                            f"{item.get('frequency', '')} — {item.get('purpose', '')}"
                        )
        return "\n".join(lines)

    @staticmethod
    def _log_cache_usage(response, label: str) -> None:
        """
        Log prompt-cache hits. The pinned anthropic==0.40.0 predates GA
        caching in its non-beta types, so whether cache_control survives to the
        wire is verified rather than assumed — this is where the evidence shows
        up. Never fatal: caching is a cost optimization, not correctness.
        """
        usage = getattr(response, "usage", None)
        if usage is None:
            return
        written = getattr(usage, "cache_creation_input_tokens", None)
        read = getattr(usage, "cache_read_input_tokens", None)
        if written or read:
            logger.debug(f"{label}: cache write={written} read={read}")


# ── Standalone smoke test ────────────────────────────────────────────────────
# python -m core.plan_manager   (offline: no API calls, renderer only)
if __name__ == "__main__":
    manager = PlanManager()
    if not manager.load():
        print(f"UNAVAILABLE: {manager.unavailable_reason}")
        sys.exit(1)

    print(f"knowledge loaded, corpus hash {manager.knowledge.corpus_hash()}")

    fake_screening = {
        "patient_label": "Huda",
        "referral_flags": [
            {"rule_id": "REF-D1", "confidence": "confident",
             "matched_because": "DHEA under consideration with no hormone labs"},
            {"rule_id": "REF-A3", "confidence": "possible",
             "matched_because": "fatigue mentioned, but no prior mitochondrial/GI support tried"},
        ],
        "plan_type": "unique",
        "standard_template_hint": None,
        "applicable_rule_ids": ["CI-THY-1", "CI-MED-8"],
        "missing_safety_fields": ["current weight"],
        "uncovered_topics": ["fibromyalgia-specific protocols"],
        "reasoning": "Hashimoto's on levothyroxine; iodine and mineral timing both constrained.",
    }
    fake_draft = {
        "patient_label": "Huda",
        "summary_of_findings": "Hashimoto's thyroiditis on levothyroxine, low ferritin.",
        "goals_timeline": {"total_months": "3", "phase_count": 2},
        "phases": [{
            "name": "Phase 1 — Foundations",
            "duration_weeks": "4",
            "supplements": [
                {"product": "Magnesium Citrate", "purpose": "Sleep and muscle support",
                 "frequency": "Daily",
                 "timing": {"upon_waking": "", "with_breakfast": "", "mid_morning": "",
                            "with_lunch": "", "mid_afternoon": "", "with_dinner": "",
                            "before_bed": "2"},
                 "comments": "Available at SEED. Space 4h from levothyroxine.",
                 "source": "03_contraindications.md#thyroid-medications"},
                {"product": "Totally Made Up Supplement", "purpose": "Testing the integrity check",
                 "frequency": "Daily", "timing": {}, "comments": "",
                 "source": "99_not_a_real_file.md#nowhere"},
            ],
            "keep_supplements": [],
            "food_therapy": [{"food": "Brazil nuts", "purpose": "Selenium", "frequency": "Daily",
                              "comments": "2-3 per day", "source": "03_contraindications.md#thyroid"}],
            "lifestyle_therapy": [],
        }],
        "testing_recommended": ["Full thyroid panel", "Ferritin"],
        "next_appointment": "Book 4 weeks after submitting test samples.",
        "not_covered_flags": [{"topic": "Fibromyalgia overlap", "why": "No document covers it"}],
        "safety_notes": [
            {"rule_id": "CI-THY-1", "how_respected": "No iodine included."},
            {"rule_id": "CI-NOT-REAL", "how_respected": "This citation is fake, should be caught."},
        ],
    }

    warnings = manager.validate_draft(fake_draft)
    print(f"\nintegrity warnings ({len(warnings)}):")
    for warning in warnings:
        print(f"  - {warning}")

    markdown = manager.render_markdown(
        fake_draft, fake_screening,
        violations=[{"rule_id": "CI-THY-1", "item": "Iodine 500mcg", "phase": "Phase 1",
                     "explanation": "Exceeds the 150 mcg ceiling in Hashimoto's."}],
        integrity_warnings=warnings,
        case_text="35yo female, Hashimoto's, on levothyroxine 75mcg.",
    )
    print(f"\nrendered {len(markdown):,} chars")
    for required in ("DRAFT — PENDING", "REFERRAL INDICATED", "CONTRAINDICATION WARNINGS",
                     "ONLY INTRODUCE A NEW SUPPLEMENT", "NOT COVERED BY YOUR DOCUMENTS",
                     "Upon waking", "Before Bed"):
        status = "ok  " if required in markdown else "MISS"
        print(f"  {status} {required!r}")

    memo = manager.render_referral_memo(fake_screening, "35yo female, considering DHEA, no labs.")
    print(f"\nreferral memo rendered {len(memo):,} chars")
    print(f"  {'ok  ' if 'No treatment plan was drafted' in memo else 'MISS'} memo states no plan drafted")
